version: "3.8"

services:
  # Base de données PostgreSQL
  postgres-intern:
    image: postgres:16-alpine
    container_name: todo-postgres-intern
    environment:
      POSTGRES_DB: todoapp_generator_intern
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopassword
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_intern_data:/var/lib/postgresql/data
      - ./database/intern/init:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    networks:
      - todo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d todoapp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period:
        40s

        # Base de données PostgreSQL
  postgres-user:
    image: postgres:16-alpine
    container_name: todo-postgres-user
    environment:
      POSTGRES_DB: todoapp_generator_user
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopassword
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
      - ./database/user/init:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    networks:
      - todo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d todoapp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Base de données PostgreSQL
  postgres-config:
    image: postgres:16-alpine
    container_name: todo-postgres-config
    environment:
      POSTGRES_DB: todoapp_generator_config
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopassword
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_config_data:/var/lib/postgresql/data
      - ./database/config/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - todo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d todoapp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: todo-api-gateway
    environment:
      PORT: 5000
      NODE_ENV: production
      PUBLIC_API_URL: http://public-api:5050
      PRIVATE_API_URL: http://private-api:5555
    ports:
      - "5000:5000"
    depends_on:
      postgres-intern:
        condition: service_healthy
      postgres-user:
        condition: service_healthy
      postgres-config:
        condition: service_healthy
      public-api:
        condition: service_started
      private-api:
        condition: service_started
    networks:
      - todo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API Publique
  public-api:
    build:
      context: ./public-api
      dockerfile: Dockerfile
    container_name: todo-public-api
    environment:
      PORT: 5050
      NODE_ENV: production
      DATABASE_URL: postgresql://todouser:todopassword@postgres:5432/todoapp
    ports:
      - "5050:5050"
    depends_on:
      postgres-user:
        condition: service_healthy
      postgres-config:
        condition: service_healthy
    networks:
      - todo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API Privée
  private-api:
    build:
      context: ./private-api
      dockerfile: Dockerfile
    container_name: todo-private-api
    environment:
      PORT: 5555
      NODE_ENV: production
      DATABASE_URL: postgresql://todouser:todopassword@postgres:5432/todoapp
    ports:
      - "5555:5555"
    depends_on:
      postgres-intern:
        condition: service_healthy
      postgres-config:
        condition: service_healthy
      postgres-user:
        condition: service_healthy
    networks:
      - todo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "3000:80"
    depends_on:
      api-gateway:
        condition: service_healthy
    networks:
      - todo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_intern_data:
    driver: local
  postgres_user_data:
    driver: local
  postgres_config_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  todo-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
