# Configuration Docker Compose pour l'API privée en production
# Service API privée isolé

services:
  # API Privée
  private-api:
    build:
      context: ../private-api
      dockerfile: Dockerfile
    container_name: todo-private-api-prod
    environment:
      API_PORT: 5555
      ENV: production
      POSTGRES_HOST: postgres-intern
      POSTGRES_PORT: 5432
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-todopassword}
      POSTGRES_DB: todoapp_generator_intern
      CACHE_HOST: redis-prod
      CACHE_PORT: 6379
      CACHE_PASSWORD: ${REDIS_PASSWORD:-""}
      CACHE_DB: 0
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key}
      CLIENT_URL: ${CLIENT_URL:-http://localhost:3000}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:3000}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "5555:5555"
    networks:
      - todo-api-network
      - todo-db-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5555/swagger/index.html",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  todo-api-network:
    external: true
    name: production_todo-api-network
  todo-db-network:
    external: true
    name: production_todo-db-network
