# Configuration Docker Compose principale pour la production
# Orchestrateur principal qui définit les réseaux partagés

services:
  # Service factice pour initialiser les réseaux
  network-init:
    image: alpine:latest
    container_name: todo-network-init
    command: ["sh", "-c", 'echo "Networks initialized" && sleep 10']
    networks:
      - todo-api-network
      - todo-frontend-network
      - todo-db-network
    restart: "no"

networks:
  # Réseau pour la communication entre APIs
  todo-api-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24

  # Réseau pour la communication frontend-gateway
  todo-frontend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24

  # Réseau pour la communication avec les bases de données
  todo-db-network:
    external: true # Créé par docker-compose.databases.yml
