# Configuration Docker Compose pour l'API Gateway en production
# Service API Gateway isolé

services:
  # API Gateway Go
  api-gateway:
    build:
      context: ../api-gateway-go
      dockerfile: Dockerfile
    container_name: todo-api-gateway-go-prod
    environment:
      PORT: 5000
      ENVIRONMENT: production
      PUBLIC_API_URL: http://public-api:5050
      PRIVATE_API_URL: http://private-api:5555
      LOG_LEVEL: ${LOG_LEVEL:-info}
      RATE_LIMIT_WINDOW: ${RATE_LIMIT_WINDOW:-60}
      RATE_LIMIT_MAX: ${RATE_LIMIT_MAX:-1000}
    ports:
      - "5000:5000"
    networks:
      - todo-api-network
      - todo-frontend-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 128M
          cpus: "0.1"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  todo-api-network:
    external: true
    name: production_todo-api-network
  todo-frontend-network:
    external: true
    name: production_todo-frontend-network
